spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/mes_produce?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '1234'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace